export const listFlag = [
  { cd: "af", n: "Afghanistan" },
  { cd: "al", n: "Albania" },
  { cd: "dz", n: "Algeria" },
  { cd: "ad", n: "Andorra" },
  { cd: "ao", n: "Angola" },
  { cd: "ag", n: "Antigua and Barbuda" },
  { cd: "ar", n: "Argentina" },
  { cd: "am", n: "Armenia" },
  { cd: "au", n: "Australia" },
  { cd: "at", n: "Austria" },
  { cd: "az", n: "Azerbaijan" },
  { cd: "bs", n: "Bahamas" },
  { cd: "bh", n: "Bahrain" },
  { cd: "bd", n: "Bangladesh" },
  { cd: "bb", n: "Barbados" },
  { cd: "by", n: "Belarus" },
  { cd: "be", n: "Belgium" },
  { cd: "bz", n: "Belize" },
  { cd: "bj", n: "Benin" },
  { cd: "bt", n: "Bhutan" },
  {
    cd: "bo",

    n: "Bolivia (Plurinational State of)",
  },
  { cd: "ba", n: "Bosnia and Herzegovina" },
  { cd: "bw", n: "Botswana" },
  { cd: "br", n: "Brazil" },
  { cd: "bn", n: "Brunei Darussalam" },
  { cd: "bg", n: "Bulgaria" },
  { cd: "bf", n: "Burkina Faso" },
  { cd: "bi", n: "Burundi" },
  { cd: "cv", n: "Cabo Verde" },
  { cd: "kh", n: "Cambodia" },
  { cd: "cm", n: "Cameroon" },
  { cd: "ca", n: "Canada" },
  { cd: "cf", n: "Central African Republic" },
  { cd: "td", n: "Chad" },
  { cd: "cl", n: "Chile" },
  { cd: "cn", n: "China" },
  { cd: "co", n: "Colombia" },
  { cd: "km", n: "Comoros" },
  { cd: "cg", n: "Congo" },
  {
    cd: "cd",

    n: "Congo, Democratic Republic of the",
  },
  { cd: "cr", n: "Costa Rica" },
  { cd: "ci", n: "Côte d'Ivoire" },
  { cd: "hr", n: "Croatia" },
  { cd: "cu", n: "Cuba" },
  { cd: "cy", n: "Cyprus" },
  { cd: "cz", n: "Czechia" },
  { cd: "dk", n: "Denmark" },
  { cd: "dj", n: "Djibouti" },
  { cd: "dm", n: "Dominica" },
  { cd: "do", n: "Dominican Republic" },
  { cd: "ec", n: "Ecuador" },
  { cd: "eg", n: "Egypt" },
  { cd: "sv", n: "El Salvador" },
  { cd: "gq", n: "Equatorial Guinea" },
  { cd: "er", n: "Eritrea" },
  { cd: "ee", n: "Estonia" },
  { cd: "sz", n: "Eswatini" },
  { cd: "et", n: "Ethiopia" },
  { cd: "fj", n: "Fiji" },
  { cd: "fi", n: "Finland" },
  { cd: "fr", n: "France" },
  { cd: "ga", n: "Gabon" },
  { cd: "gm", n: "Gambia" },
  { cd: "ge", n: "Georgia" },
  { cd: "de", n: "Germany" },
  { cd: "gh", n: "Ghana" },
  { cd: "gr", n: "Greece" },
  { cd: "gd", n: "Grenada" },
  { cd: "gt", n: "Guatemala" },
  { cd: "gn", n: "Guinea" },
  { cd: "gw", n: "Guinea-Bissau" },
  { cd: "gy", n: "Guyana" },
  { cd: "ht", n: "Haiti" },
  { cd: "hn", n: "Honduras" },
  { cd: "hu", n: "Hungary" },
  { cd: "is", n: "Iceland" },
  { cd: "in", n: "India" },
  { cd: "id", n: "Indonesia" },
  { cd: "ir", n: "Iran (Islamic Republic of)" },
  { cd: "iq", n: "Iraq" },
  { cd: "ie", n: "Ireland" },
  { cd: "il", n: "Israel" },
  { cd: "it", n: "Italy" },
  { cd: "jm", n: "Jamaica" },
  { cd: "jp", n: "Japan" },
  { cd: "jo", n: "Jordan" },
  { cd: "kz", n: "Kazakhstan" },
  { cd: "ke", n: "Kenya" },
  { cd: "ki", n: "Kiribati" },
  {
    cd: "kp",

    n: "Korea (Democratic People's Republic of)",
  },
  { cd: "kr", n: "Korea, Republic of" },
  { cd: "kw", n: "Kuwait" },
  { cd: "kg", n: "Kyrgyzstan" },
  {
    cd: "la",

    n: "Lao People's Democratic Republic",
  },
  { cd: "lv", n: "Latvia" },
  { cd: "lb", n: "Lebanon" },
  { cd: "ls", n: "Lesotho" },
  { cd: "lr", n: "Liberia" },
  { cd: "ly", n: "Libya" },
  { cd: "li", n: "Liechtenstein" },
  { cd: "lt", n: "Lithuania" },
  { cd: "lu", n: "Luxembourg" },
  { cd: "mg", n: "Madagascar" },
  { cd: "mw", n: "Malawi" },
  { cd: "my", n: "Malaysia" },
  { cd: "mv", n: "Maldives" },
  { cd: "ml", n: "Mali" },
  { cd: "mt", n: "Malta" },
  { cd: "mh", n: "Marshall Islands" },
  { cd: "mr", n: "Mauritania" },
  { cd: "mu", n: "Mauritius" },
  { cd: "mx", n: "Mexico" },
  {
    cd: "fm",

    n: "Micronesia (Federated States of)",
  },
  { cd: "md", n: "Moldova, Republic of" },
  { cd: "mc", n: "Monaco" },
  { cd: "mn", n: "Mongolia" },
  { cd: "me", n: "Montenegro" },
  { cd: "ma", n: "Morocco" },
  { cd: "mz", n: "Mozambique" },
  { cd: "mm", n: "Myanmar" },
  { cd: "na", n: "Namibia" },
  { cd: "nr", n: "Nauru" },
  { cd: "np", n: "Nepal" },
  { cd: "nl", n: "Netherlands" },
  { cd: "nz", n: "New Zealand" },
  { cd: "ni", n: "Nicaragua" },
  { cd: "ne", n: "Niger" },
  { cd: "ng", n: "Nigeria" },
  { cd: "mk", n: "North Macedonia" },
  { cd: "no", n: "Norway" },
  { cd: "om", n: "Oman" },
  { cd: "pk", n: "Pakistan" },
  { cd: "pw", n: "Palau" },
  { cd: "pa", n: "Panama" },
  { cd: "pg", n: "Papua New Guinea" },
  { cd: "py", n: "Paraguay" },
  { cd: "pe", n: "Peru" },
  { cd: "ph", n: "Philippines" },
  { cd: "pl", n: "Poland" },
  { cd: "pt", n: "Portugal" },
  { cd: "qa", n: "Qatar" },
  { cd: "ro", n: "Romania" },
  { cd: "ru", n: "Russian Federation" },
  { cd: "rw", n: "Rwanda" },
  { cd: "kn", n: "Saint Kitts and Nevis" },
  { cd: "lc", n: "Saint Lucia" },
  {
    cd: "vc",

    n: "Saint Vincent and the Grenadines",
  },
  { cd: "ws", n: "Samoa" },
  { cd: "sm", n: "San Marino" },
  { cd: "st", n: "Sao Tome and Principe" },
  { cd: "sa", n: "Saudi Arabia" },
  { cd: "sn", n: "Senegal" },
  { cd: "rs", n: "Serbia" },
  { cd: "sc", n: "Seychelles" },
  { cd: "sl", n: "Sierra Leone" },
  { cd: "sg", n: "Singapore" },
  { cd: "sk", n: "Slovakia" },
  { cd: "si", n: "Slovenia" },
  { cd: "sb", n: "Solomon Islands" },
  { cd: "so", n: "Somalia" },
  { cd: "za", n: "South Africa" },
  { cd: "ss", n: "South Sudan" },
  { cd: "es", n: "Spain" },
  { cd: "lk", n: "Sri Lanka" },
  { cd: "sd", n: "Sudan" },
  { cd: "sr", n: "Surin" },
  { cd: "se", n: "Sweden" },
  { cd: "ch", n: "Switzerland" },
  { cd: "sy", n: "Syrian Arab Republic" },
  { cd: "tj", n: "Tajikistan" },
  {
    cd: "tz",

    n: "Tanzania, United Republic of",
  },
  { cd: "th", n: "Thailand" },
  { cd: "tl", n: "Timor-Leste" },
  { cd: "tg", n: "Togo" },
  { cd: "to", n: "Tonga" },
  { cd: "tt", n: "Trind Tobago" },
  { cd: "tn", n: "Tunisia" },
  { cd: "tr", n: "Türkiye" },
  { cd: "tm", n: "Turkmenistan" },
  { cd: "tv", n: "Tuvalu" },
  { cd: "ug", n: "Uganda" },
  { cd: "ua", n: "Ukraine" },
  { cd: "ae", n: "United Arab Emirates" },
  {
    cd: "gb",

    n: "United Kingdom of Great Britain and Northern Ireland",
  },
  { cd: "us", n: "United States of America" },
  { cd: "uy", n: "Uruguay" },
  { cd: "uz", n: "Uzbekistan" },
  { cd: "vu", n: "Vanuatu" },
  {
    cd: "ve",

    n: "Venezuela (Bolivarian Republic of)",
  },
  { cd: "vn", n: "Viet Nam" },
  { cd: "ye", n: "Yemen" },
  { cd: "zm", n: "Zambia" },
  { cd: "zw", n: "Zimbabwe" },
];

export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Surin",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinmp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
