export const types = {
  SET_DRAWN_COUNTRY: "SET_DRAWN_COUNTRY",
  SET_DRAWN_COUNTRIES: "SET_DRAWN_COUNTRIES",
  SET_WIKI_CONTENT: "SET_WIKI_CONTENT",
  SET_WIKI_IMAGE: "SET_WIKI_IMAGE",
  SET_DRAWN_CITY: "SET_DRAWN_CITY",
  SET_DRAWN_CITY_COORDS: "SET_DRAWN_CITY_COORDS",
  SET_WIKI_COUNTRY_INFO: "SET_WIKI_COUNTRY_INFO",
  SET_WIKI_CITY_INFO: "SET_WIKI_CITY_INFO",
};
